version: '3.8'

services:
  # TurboVault Server
  turbovault:
    build:
      context: .
      dockerfile: Dockerfile
    image: turbovault-server:latest
    container_name: turbovault
    user: obsidian
    volumes:
      - ./example-vault:/var/obsidian-vault
    environment:
      - RUST_LOG=info
      - OBSIDIAN_VAULT_PATH=/var/obsidian-vault
    healthcheck:
      test: [CMD, /usr/local/bin/turbovault, --help]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    stdin_open: true
    tty: true
